apiVersion: v1
kind: Service
metadata:
    name: "collateral-ce61"
    labels:
        app: "collateral-ce61"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "collateral-ce61"